services:
  strapi-webhook-proxy:
    build: .
    container_name: strapi-webhook-actions-proxy
    restart: unless-stopped
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
